2 create architecture
Zone-O/Zone-o-server pull request #1
Opened 2023-06-01 17:43 UTC by LucasTesnier

Create the basic server architecture and a prebase for @31Nathan 
(Moving the work of @TomDUVAL-MAHE )

2023-06-01 18:31 UTC, 31Nathan submitted a review, later dismissed
Seems good to me, I will add the prisma schema after

2023-06-07 19:19 UTC, 31Nathan approved these changes, later dismissed

2023-06-08 11:29 UTC, osvegn commented
Need to update 'tests/index.test.js' with the import '../index.js' to the new filename @LucasTesnier

2023-06-12 10:49 UTC, osvegn requested changes
Unsecured password defined
config route seems useless

2023-06-12 10:49 UTC, osvegn commented on database/dump.sql
> +ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'password';
Unsecured

2023-06-12 10:49 UTC, osvegn commented on sources/server_app.js
> +app.get('/about.json', async (req, res) => {
why this route is usefull ?

2023-06-12 11:49 UTC, osvegn approved these changes

2023-06-13 07:00 UTC, 31Nathan approved these changes

2023-06-13 07:05 UTC, merged